baseurl = "/"
languageCode = "en-us"
languageLang = "en"
title = "Lakeview Plantation"

# Landing Page theme from https://themes.gohugo.io/landing-page-hugo/
theme = "startbootstrap-clean-blog"

[params]
    DateForm = "Mon, Jan 2, 2006"
    Author = "Susan Murphy"
    Description = "Lakeview Plantation Homeowners Association member site"

#[[params.social]]
#    title = "email"
#    icon = "envelope-o"
#    url = "mailto:smurph7@emory.edu"
#[[params.social]]
#    title = "twitter"
#    icon = "twitter"
#    url = "https://twitter.com/SBootstrap"
#[[params.social]]
#    title = "github"
#    icon = "github"
#    url = "https://github.com/IronSummitMedia/startbootstrap"
#[[params.social]]
#    title = "linkedin"
#    icon = "linkedin"
#    url = "http://linkedin.com/in/yourusername"
[[menu.main]]
    name = "Home"
    url  = "/"
    weight = 5

# RSS, categories and tags disabled for an easy start
# See configuration options for more details: 
# https://gohugo.io/getting-started/configuration/#toml-configuration
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]
