
backend:
  name: github
  repo: CandescentMedia/lakeview-hoa-web
  branch: master # Branch to update

media_folder: "/site/media/uploads" # Media files will be stored here
public_folder: "/media/uploads" # The src attribute for uploaded media

collections:
  # Used in routes, ie.: /admin/collections/:slug/edit
  - name: "post"
    # Used in the UI, ie.: "New Post"
    label: "Post"
    # The path to the folder where the documents are stored
    folder: "site/content/post"
    # Allow users to create new documents in this collection
    create: true
    # Filename template e.g. YYYY-MM-DD-title.md
    slug: "{{slug}}"
    # The fields each document in this collection have
    fields:
      - {label: "Document Name", name: "title", widget: "string", tagname: "h1"}
      # Use required: false instead of optional: true - https://github.com/netlify/netlify-cms/issues/315
      - {label: "Description", name: "description", widget: "string", tagname: "h3"}
      - {label: "File", name: "fileurl", widget: "file"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}
